#!/bin/bash

dir=$1
RESULT=`ls -a $dir | sort`
declare -a ARRAY
declare -a ARRAY1
declare -a ARRAY2
let count1=0
let count2=0

for FILE in $RESULT
do
    if [ ! -L "$dir/$FILE" ]
    then
	if [ -f "$dir/$FILE" ]
	then
	    if [ "${FILE:0:1}" == "." ]
	    then
		ARRAY1[$count1]="$dir/$FILE"
		let count1=count1+1
	    else
		ARRAY2[$count2]="$dir/$FILE"
		let count2=count2+1
	    fi
       	fi
    fi

done

ARRAY=("${ARRAY1[@]}" "${ARRAY2[@]}")
let count=$((count1 + count2))

for ((i=0; i<$count; i++))
do
    for((j=$((i + 1)); j<$count; j++))
    do
	cmp -s -- "${ARRAY[$i]}" "${ARRAY[$j]}"
	if [ $? -eq 0 ]
	then
	     ln -f -- "${ARRAY[$i]}" "${ARRAY[$j]}"
	fi
    done
done